### ISSUE TITLE
CI tool for model changes check

### ISSUE THREAD

**Issue by minox86** [twinlogix/mondrian-framework#168]
Having a formal model of the API can be extremely useful to check for unexpected breaking changes, that's typically one of the most common issue in API development.

The idea could be to develop a tool, maybe a CLI tool, to look for breaking changes between two commits of a Mondrian project. This tool can be configured in a CI pipeline to show the differences between two versions in terms of API specification, highlighting breaking changes.

**Comment by edobrb** [comment]
Useful tools:
 - GraphQL
   - https://the-guild.dev/graphql/inspector/docs/commands/diff
 - OpenAPI
   -  https://github.com/Tufin/oasdiff now working with circular references
   - https://github.com/bump-sh/cli works well but used a third party service (closed source)
   - https://github.com/pb33f/openapi-changes super cool, probably we'll go with these

**Comment by edobrb** [comment]
#220 needed
