### ISSUE TITLE
Add `Project` type

### ISSUE THREAD

**Issue by edobrb** [twinlogix/mondrian-framework#32]
```typescript
export type Project<T extends types.Type, P extends projection.FromType<T>> = never // A subset of types.Infer<T> based on P
```

**Comment by giacomocavalieri** [comment]
Closing this with [fa76425](https://github.com/twinlogix/mondrian-framework/commit/fa7642524826f6be96cd3e334aff68cae2f59996)
I ended up with the `projection.Infer` name

**Comment by edobrb** [comment]
The `projection.Infer` does not accept a projection P. In ad383a2b9a6637bd78acbe52b767d0ea0cc2bb8d I've implemented it as `projection.Project`

**Comment by edobrb** [comment]
This is still needed but only by `module` package. I would implement it directly inside this package.
