### ISSUE TITLE
Add `tuple` type

### ISSUE THREAD

**Issue by edobrb** [twinlogix/mondrian-framework#35]
```typescript
const t = types.tuple(types.number(), types.string(), types.boolean())
type T = types.Infer<typeof t> // [number, string, boolean]
```

**Comment by edobrb** [comment]
GraphQL generation could be a [problem](https://github.com/graphql/graphql-spec/issues/534)

**Comment by giacomocavalieri** [comment]
Also we should do this only after we established if #36 is feasible (so we don't have an additional piece of code that would break with that change)
