### ISSUE TITLE
Add `rate-limiting` capability

### ISSUE THREAD

**Issue by edobrb** [twinlogix/mondrian-framework#40]
We can get inspiration from [CloudFlare](https://blog.cloudflare.com/counting-things-a-lot-of-different-things/) solution.

Feature requests:
 - [x] possible to define multiple limits per function based on a custom logic (for example the `login` function must be limited with a maximum 20 requests per hour by ip-email combination, and with a maximum of 20 request per minute by ip independently)
 - [ ] possible to define the strategy: leaky-bucket or sliding-window
 - [x] possible to define the memory support: redis or local
 
 
 An example could be:
 ```typescript
const myModule = m.module({
  name: 'example',
  version: '1.0.0',
  functions: {
    definitions: functions,
    options: {
      login: {
        rateLimits: [
          {
            description: 'Maximum 20 attempts per hour', // could be exported to openapi & graphql
            rate: '20/hour',
            key: (context, input) => `login-${input.email}-${context.request.ip}`,
            strategy: undefined // default is set to 'sliding-window'
          },
          {
            rate: '20/minute',
            key: (context, input) => `login-${context.request.ip}`,
            strategy: 'leaky-bucket'
          },
        ],
      },
    },
  },
  options: {
    rateLimit: {
      strategy: 'sliding-window',
      support: ratelimiter.redis({ endpoint: '...' })
    }
  }
 })
 ```
 
As a first step we could only implement the sliding-windows strategy described by CloudFlare

**Comment by minox86** [comment]
Upvote!

Il Gio 10 Ago 2023, 10:28 Edoardo Barbieri ***@***.***> ha
scritto:

**Comment by edobrb** [comment]
Supported with a middleware -> #85
