### ISSUE TITLE
Improve number generators' options

### ISSUE THREAD

**Issue by giacomocavalieri** [twinlogix/mondrian-framework#41]
The generator for number types currently does not generate the `minimum`/`maximum`/`exclusiveMinimum`/`exclusiveMaximum` options. Previously we were naive in the implementation and this resulted in generators that would output invalid types.
I couldn't figure out a nice way to do it so I'm opening this issue as a future reminder to put more work into it.

Thinking about this, the options generator _should_ generate non sensical options (fundamental to properly test the implementations relying on the options) but the `fromType` generator should refuse to generate a type for those options since it would be impossible (however, if it detects options for which it's impossible to generate a number it should throw an exception, not hang forever like it previously did)

**Comment by edobrb** [comment]
fixed at bf007e348518f6a43770e58a4764659d48411bb0
