### ISSUE TITLE
`merge`, `omit`, `pick` and `partial` not building with recursive type

### ISSUE THREAD

**Issue by edobrb** [twinlogix/mondrian-framework#42]
```typescript
const User = () =>
    types.object({
      email: types.string(),
      password: types.string(),
      friend: types.partial(User),
})
//'User' implicitly has return type 'any' because it does not have a return type annotation
// and is referenced directly or indirectly in one of its return expressions.ts(7023)
```

**Comment by edobrb** [comment]
After many attempts I came to the conclusion that (perhaps the only) possible solution would be to define `merge`, `omit`, `pick` and `partial` as `Type`s and construct the inferred type inside the `Infer` instead of trying to materialize the type directly into the return type of their constructors.

This minimal examples are not currently working:
```typescript
const t1 = () => object({ a: pick(t1, { a: true }), b: number() })
type ExpectedT1 = { a: Pick<ExpectedT1, 'a'>; b: number }
const t2 = () => object({ a: omit(t2, { a: true }), b: number() })
type ExpectedT2 = { a: Omit<ExpectedT2, 'a'>; b: number }
const t3 = () => object({ a: partial(t3), b: number() })
type ExpectedT3 = { a: Partial<ExpectedT3>; b: number }
const t4 = () => object({ a: merge(t4, object({ c: number() })), b: number() })
type ExpectedT4 = { a: ExpectedT4 & { c: number }; b: number }
```

This would be the `Type` type after the refactor:

```typescript
export type Type = Lazy<
  | NumberType
  | StringType
  | BooleanType
  | EnumType<any>
  | LiteralType<any>
  | UnionType<any>
  | ObjectType<any, any>
  | ArrayType<any, any>
  | OptionalType<any>
  | NullableType<any>
  | ReferenceType<any>
  | Merge<any, any, any> //this <T1, T2, M>
  | PickType<any, any, any> // this <T, Fields, M>
  | OmitType<any, any> // this  <T, Fields, M>
  | PartialType<any, any> // this <T, M>
  | CustomType<any, {}, any>
>
```

If anyone could think of another approach that would be great.

**Comment by giacomocavalieri** [comment]
I can look into it when I'm done with the projections, I'd like to think of a way to avoid adding more types into Mondrian's type system (it may not be possible though)

Do you have code for your experiments I could look into to see what didn't work?

**Comment by edobrb** [comment]
Sorry, I reverted all the various attempts I had made :(
Anyways, if you can make this type compile it means you've succeeded!
```typescript
const type = () => object({ field: partial(type) })
```

**Comment by giacomocavalieri** [comment]
Great thanks! I'll try my best 👍

**Comment by edobrb** [comment]
Also `types.partialDeep` has the same problem. However, after some thinking I believe that's a legit limitation. We could just ignore it or provide this feature at type-system level.

**Comment by edobrb** [comment]
This feature is deprecated
