### ISSUE TITLE
`withDefault` should also be considered in decoding

### ISSUE THREAD

**Issue by edobrb** [twinlogix/mondrian-framework#43]
The default is very useful when used inside input types. For example:

```typescript
const QueryInput = types.object({
  search: types.string().optional(),
  skip: types.number().optional().withDefault(0),
  take: types.number().optional().withDefault(20),
})

const function = buildFunction({
  input: QueryInput,
  output: ...,
  async apply({ input }) {
    // input.skip & input.take should be always defined
    //...
})
```

it would be cool if we implement 2 slightly different variants of Infer:
```typescript
// type used by the function implementation
type QueryInput = types.InferInput<typeof QueryInput> // { search?: string, skip: number, take: number }

// type used by the caller
type QueryInput = types.Infer<typeof QueryInput> // { search?: string, skip?: number, take?: number }
```

Maybe this would be clearer if we reintroduce the `DefaultDecorator` that we'll be called `DefaultType` and used as follows:
```typescript
const QueryInput = types.object({
  search: types.string().optional(),
  skip: types.number().default(0),
  take: types.number().default(20),
})
```
To me the latter communicates the intent more clearly instead of `optional().withDefault(...)`

**Comment by giacomocavalieri** [comment]
I'm not too sure about making the `withDefault` one of the elements of the type system. It only makes sense for optional fields of an object and nowhere else in the type system.

Also we could achieve the same expected behavior you describe in your last code example with what we currently have by simply adding another function to the current available types:

```ts
type NumberType = {
  default(n: Infer<NumberType>): OptionalType<NumberType> = types.optional(this).withDefault(n)
}
```

And the code would look and behave exactly the same without the added complexity of a new type in the Mondrian's type system:
```ts
const QueryInput = types.object({
  search: types.string().optional(),
  skip: types.number().default(0),   // <- inferred as `number | undefined`
  take: types.number().default(20),  // <- inferred as `number | undefined`
})
```

As for the default value in the decoding process, shouldn't we let the user decide when/if they want to use it? They always have access to it if they need it, also always using the fallback default when decoding could be limiting (for example if my business logic needs to perform different actions if the value is present or not)

If someone wants the default they could still do something relatively easy and they have the possibility to choose:

```ts
const model = types.object({ field: types.number().withDefault(10) })
const decoded = decoder.decode(model, rawValue)
decoded.map((value) => {
  if (value.field) {
    businessLogic(value.field)
  } else {
    console.log("There was a missing field, taking corrective action and using the fallback value")
    takeCorrectiveAction() // some separate logic that needs to fire if the value is missing
    businessLogic(model.types.field.defaultValue) // use the default value
  }
})
```

**Comment by edobrb** [comment]
> I'm not too sure about making the `withDefault` one of the elements of the type system. It only makes sense for optional fields of an object and nowhere else in the type system.

I agree to keep it simple as possible. Anyways the `default` makes sense with every type. For example i would like to do:
```typescript
const t1 = types.object({ field: types.number() }).default({ field: 1 })
const t2 = types.union({ variant1: types.number(), variant2: types.string() }).default({ variant1: 1 })
```

> As for the default value in the decoding process, shouldn't we let the user decide when/if they want to use it? They always have access to it if they need it, also always using the fallback default when decoding could be limiting (for example if my business logic needs to perform different actions if the value is present or not)

Until now, I've only used the `default` for input types (decoding phase), so if it doesn't make sense to exist for input types in my opinion we can remove support for `default` altogether. It's a feature with the sole purpose of facilitating the definition of types and functions by removing part of the boiler plate code that often happens to be written.

Also semantically `Optional<T> != Default<T>`. `Optional<T>` is simply `T | undefined` while `Default<T>` brings with it more information (besides the default value). `Default<T>` indicates that the input value (user side) is optional, while the decoded input value (developer side) has always a value, therefore the difference between these two:
```typescript
// type used by the function implementation
type QueryInput = types.InferInput<typeof QueryInput> // { search?: string, skip: number, take: number }

// type used by the caller
type QueryInput = types.Infer<typeof QueryInput> // { search?: string, skip?: number, take?: number }
```

It's a matter of understanding whether it's worth implementing this functionality. If we decide not to, I would also remove the `.withDefault`

**Comment by giacomocavalieri** [comment]
Ah now I see, why would we need two slightly different implementations though? If a value is defined as having a default this way, why would we ever infer it as optional like you showed?

**Comment by edobrb** [comment]
Maybe I swapped the names, `Infer` should give the type with no optionals while `InferInput` with the optionals. Here's an example of why we need two different Infer:
```typescript
const QueryInput = types.object({
  search: types.string().optional(),
  skip: types.number().default(0),
  take: types.number().default(20),
})
const QueryOutput = types.string().array()

function query = functions.context<...>().build({
  input: QueryInput,
  output: QueryOutput,
  apply({ input: { search, skip, take }, context }) {
    return context.db.find(search, skip, take) //here skip & take are always number
  }
})
const module = module.functions({ definitions: { query }).context(...).build()
const client = sdk.build({ module })

//calling the function
const  results: string[] = await client.query({ search: '123' }) //here skip & take could be undefined
```

If we want to avoid type-system pollution I could implement a private utility `InferInput` inside the `packages/module/sdk.ts`. However, this doesn't save us from implementing the default decorator inside the type system if we want this feature.

**Comment by edobrb** [comment]
For simplicity, I would propose removing the `.withDefault` and labeling this issue as low-priority. If in the future we see that it's highly requested as a feature, we'll consider implementing it.

**Comment by giacomocavalieri** [comment]
Yes I agree, it can surely be helpful but I'm afraid it would make type inference way more complicated than it currently is so I'd not prioritise this, I removed `defaultValue` in [commit eea60c](https://github.com/twinlogix/mondrian-framework/pull/25/commits/eea60c4b2c047c34875bfca0306a2210daf02413)

**Comment by edobrb** [comment]
Will not implement this because on the graphql and openapi generation we must implement two different behaviours. If the default is on input type the converted type should be optional. If the default is on output type the converted type should be not modified. 
This add too much complexity for now.
